export const NAV_LABELS = {
  SERVICES: "Usługi",
  COMPLIANCE_SUBSCRIPTION: "Subskrypcja Zgodności",
  SMOKE_ALARM_CHECK: "Przegląd Czujników Dymu",
  ELECTRICAL_CHECK: "Przegląd Instalacji Elektrycznej",
  GAS_CHECK: "Przegląd Instalacji Gazowej",
  CARAVAN_GAS_CHECK: "Przegląd Instalacji w Przyczepach Kempingowych",
  SWITCHBOARD_UPGRADE: "Modernizacja Rozdzielnicy Elektrycznej",
  PLUMBING_SERVICES: "Usługi Hydrauliczne",
  INCLUSIONS_EXCLUSIONS: "Zakres Usługi i Wyłączenia",

  SOLUTIONS: "Rozwiązania",
  FOR_PROPERTY_MANAGERS: "Dla Zarządców Nieruchomości",
  FOR_LANDLORDS: "Dla Właścicieli Mieszkań na Wynajem",
  FOR_BUILDING_MANAGERS: "Dla Administratorów Budynków",
  FOR_HOMEOWNERS: "Dla Właścicieli Domów",
  FOR_REAL_ESTATE: "Dla Biur Nieruchomości",

  FAQ: "FAQ",
  ABOUT_US: "O nas",
  BOOK_NOW: "Zarezerwuj Przegląd",
  CONTACT_US: "Kontakt",
  LEGISLATION: "Legislacja",
  PRIVACY_POLICY: "Polityka Prywatności",
};
