export const GeneralPlumbingContent = {
  bannerTitle: "Usługi hydrauliczne",
  section1: {
    title: "Profesjonalne usługi hydrauliczne",
    paragraphs: [
      `Oferujemy kompleksowe wsparcie w szerokim zakresie usług – od napraw przecieków i instalacji dachowych po drobne prace konserwacyjne. Potrzebujesz sprawdzonego hydraulika? Przekonaj się sam, jak bardzo dbamy o jakość obsługi i pełne zadowolenie klientów.`,
      "Nasze główne usługi:",
      `Wycieki wody (w tym pęknięte rury, nieszczelności prysznicowe)`,
      `Naprawa wszystkich rodzajów kranów`,
      `Naprawa i montaż podgrzewaczy wody`,
      `Naprawa i montaż urządzeń gazowych`,
      `Lokalizacja i naprawa wycieków gazu, wymiana instalacji`,
      `Usuwanie zatorów w instalacjach`,
      `Inspekcja kanalizacji kamerą (CCTV)`,
      `Lokalizacja rur i przewodów`,
      `Usuwanie przecieków z dachów, balkonów i okien`,
      `Złożone instalacje gazowe w lokalach komercyjnych`,
      `Remonty instalacji hydraulicznych w szkołach, domach opieki, restauracjach itp.`,
      `Awaryjne naprawy hydrauliczne`,
      `Naprawy sieci sanitarnych dla wspólnot mieszkaniowych i zarządców nieruchomości komercyjnych`,
    ],
  },
  section2: {
    title: "Hydraulik do domu i firmy",
    paragraphs: [
      `Usługi hydrauliczne są podstawą bezpiecznego i sprawnego funkcjonowania zarówno budynków mieszkalnych, jak i obiektów komercyjnych.`,
      `Zdrowie i higiena: zapewniają czystą wodę i prawidłowe odprowadzanie ścieków.`,
      `Bezpieczeństwo: ograniczają ryzyko zalania i uszkodzeń.`,
      `Ciągłość działania: zapobiegają przestojom w firmach.`,
      `Oszczędności: zmniejszają rachunki i unikają kosztownych napraw awaryjnych.`,
      `Komfort: poprawiają warunki życia i pracy.`,
      `Zgodność z przepisami: spełniają normy instalacyjne.`,
      `Ochrona środowiska: promują zrównoważone rozwiązania.`,
      `Profesjonalny hydraulik to gwarancja sprawnych i bezpiecznych instalacji wodnych, co wpływa na komfort mieszkańców oraz działanie firm.`,
    ],
  },
  section3: {
    title: "Kiedy skontaktować się z hydraulikiem?",
    paragraphs: [
      `Wiedza, kiedy wezwać fachowca, jest kluczowa dla bezpieczeństwa i stanu technicznego nieruchomości. Oto sytuacje, w których pomoc hydraulika jest niezbędna:`,
      `Ciągłe wycieki wody: prowadzą do uszkodzeń i pleśni.`,
      `Problemy z ciśnieniem wody: mogą świadczyć o poważnych usterkach.`,
      `Zatory w kanalizacji: objawiają się zapachami i niedrożnością.`,
      `Brak ciepłej wody: może wskazywać na awarię podgrzewacza.`,
      `Plamy na ścianach: mogą oznaczać ukryty wyciek.`,
      `Zabarwiona woda: może wskazywać na korozję rur.`,
      `Bulgotanie w rurach: świadczy o zatorach.`,
      `Zapach gazu: natychmiast wezwij fachowca i opuść budynek.`,
      `Szybka interwencja hydraulika pozwala uniknąć kosztownych napraw i poprawia bezpieczeństwo nieruchomości.`,
    ],
  },
  seo: {
    title: "Usługi hydrauliczne",
    description:
      "Nasi profesjonalni hydraulicy oferują fachowe naprawy instalacji ciepłej wody i przecieków, serwis podgrzewaczy gazowych i kompleksowe rozwiązania hydrauliczne.",
  },
};
